trailing_semicolon = false
spaces_around_ranges = false
reorder_imports = true
newline_style = 'Unix'
max_width = 100
comment_width = 100
wrap_comments = true
chain_width = 80
match_arm_leading_pipes = 'Preserve'
binop_separator = 'Back'
match_block_trailing_comma = true
trailing_comma = 'Vertical'
use_field_init_shorthand = true
reorder_impl_items = false
use_small_heuristics = 'Max'
imports_granularity = 'Crate'
hard_tabs = true
match_arm_blocks = false
